### ISSUE TITLE
Extension notifies  allocine/twigcs as requirement 

### ISSUE THREAD

**Issue by jevgen** [Cerzat43/vscode-twigcs#14]
I believe it is obsolete notification. 
But after specifying path explicitly in settings.json in VSCode
    "twigcs.executablePath": "/Users⁩/myuser/.composer⁩/vendor⁩/friendsoftwig⁩/twigcs⁩/bin⁩",
notification does not go off.

**Comment by Cerzat43** [comment]
This parameter must contain the name of the executable "twigcs" not only the path to it. Can you confirm that this is this? Otherwise, I will look at my return from vacation.

**Comment by Cerzat43** [comment]
@jevgen is it ok with `/Users⁩/myuser/.composer⁩/vendor⁩/friendsoftwig⁩/twigcs⁩/bin/twigcs` ?

**Comment by hacknug** [comment]
@Cerzat43 doesn't work for me with `/Users/nestor/.composer/vendor/friendsoftwig/twigcs/bin/twigcs`. Guessing this issue is the same as #16
