### ISSUE TITLE
A line should not end with blank space(s).

### ISSUE THREAD

**Issue by pawelsla** [Cerzat43/vscode-twigcs#15]
I’ve got warning messages from TwigLint: “A line should not end with blank space(s).”  I don't where is problem? It's generate on this code line in Grav CMS:

` <h4 class="text-center"><u>{{ page.title }}</u></h4>`

**Comment by Cerzat43** [comment]
Sorry about this...
I am currently on vacation, I look at the problem you encounter when I return.

**Comment by Cerzat43** [comment]
Hi @pawelsla 

I just looked at your problem, I think the line you give as an example has a useless space at the end.
I advise you to use the option `"files.trimTrailingWhitespace": true,` in your configuration file, this will remove all these useless spaces and should fix this problem.

Can you confirm that this is this?

Thanks
