### ISSUE TITLE
Variables used within a template include (with 'with') are ignored in the use-count

### ISSUE THREAD

**Issue by Friksel** [Cerzat43/vscode-twigcs#17]
First of all thanks a lot for this extension. It's nice to have these checks in Twig files!

There's one minor issue I found though; the linter seems to ignore variables being used in template includes 'with's as it's mentioning a problem that a variable isn't used, even though it is sent with the template include.

But other than that; great plugin. Keep up the great work!

![unused-variable](https://user-images.githubusercontent.com/3089978/79964285-c5605700-848a-11ea-8fb1-c79b6b76d771.jpg)

[Edit] Using version 1.1.0 btw

**Comment by Cerzat43** [comment]
Thanks for your message. I'll try to fix it soon.

**Comment by Friksel** [comment]
@Cerzat43  Thanks! Really appreciated!

**Comment by Cerzat43** [comment]
There is an issue in the friendsoftwig/twigcs project (used by this extention) to fix this problem : https://github.com/friendsoftwig/twigcs/issues/35
This issue will fix the problem.

In additionnal, I'll work on the compatibility with their version 4 to be ready when it'll be a RC.

Thanks for your messages.

**Comment by Friksel** [comment]
> There is an issue in the friendsoftwig/twigcs project (used by this extention) to fix this problem : [friendsoftwig/twigcs#35](https://github.com/friendsoftwig/twigcs/issues/35)
> This issue will fix the problem.
> 
> In additionnal, I'll work on the compatibility with their version 4 to be ready when it'll be a RC.
> 
> Thanks for your messages.

Thanks for your response and nice to see you are actively maintaining this.
Unfortunately the issue in the other lib seems to be standing two years already to my surprise. Just added a comment to the thread there and hope they could fix these issues anytime soon.

For now I will think about if I will continue using this extension or turn it off, as it's now throwing all kinds of untrue warnings not really helping while developing. Nothing to do with your work ofcoarse.

Hopefully twigcs will fix this, or maybe it's fixed in v4? Anyway, thanks again for your quick and helpful responses.

**Comment by Cerzat43** [comment]
I think, it'll be fix with their version 4.
I'll try to confirm it.

**Comment by Cerzat43** [comment]
@Friksel I have no longer this issue with friendsoftwig/twigcs version v3.2.2
Can you confirm that it's ok for you too ?

**Comment by Friksel** [comment]
@Cerzat43 Great. Though I just tried upgrading to 3.2.2, but there seems to be a problem to do that.

I'm running php 7.1.16 because of an older CMS system I'm using, and it seems like it needs at least php 7.2.5. I'm in the process of getting rid of the older CMS and moving to another CMS, but it takes a while to definitely move over and use a newer php-version that runs twigcs version 3.2.2.

So unfortunately can't verify it's working here at the moment.

![image](https://user-images.githubusercontent.com/3089978/91550663-2a402800-e929-11ea-8402-346627918ca7.png)

**Comment by Cerzat43** [comment]
Ok I understand, thanks for your message.
