### ISSUE TITLE
Variables used in a switch are ignored in the use-count

### ISSUE THREAD

**Issue by Friksel** [Cerzat43/vscode-twigcs#18]
I put his one in a different issue to keep things seperated.

The extension throws warnings on a variable not being used, even though it IS used inside a switch statement:

``` 
{% set type = craft.app.request.getParam('param')|default(null) %}

{% switch type %}
    {% case 'some-value' %}
        {# ... #}
{% endswitch %}
```

**Comment by Cerzat43** [comment]
Hi @Friksel 
Thanks for your message.
I close this issue because it's the same issue as this one : https://github.com/Cerzat43/vscode-twigcs/issues/17
