### ISSUE TITLE
Ability to specify ruleset class

### ISSUE THREAD

**Issue by joelambert** [Cerzat43/vscode-twigcs#19]
It would be useful to be able to pass custom CLI options to `twigcs`.

We use a slightly modified rule set which can only be configured using the `--ruleset` option. This works fine on our CI server where we run the CLI command direct but not currently in the editor.

Would it be possible to add this a VSCode settings?

**Comment by nikolenko-dmitriy** [comment]
We also really need this improvement for the custom ruleset option.

**Comment by Cerzat43** [comment]
Thank you for your messages.
I'll work on it.

**Comment by Cerzat43** [comment]
If you are agree, I'll change the title of this issue to `Ability to specify ruleset class`.
There may be conflicts or problems if I allow all CLI settings.

**Comment by joelambert** [comment]
Sure thing 👍

**Comment by Cerzat43** [comment]
Thanks @joelambert.

I'm working on it.

**Comment by Cerzat43** [comment]
Done, @joelambert could you check if it's ok for you too with the new version v1.3.0 ?
Thanks a lot !
