### ISSUE TITLE
After upgrading from 1.1.0 VSCode is not highlighting errors

### ISSUE THREAD

**Issue by sirchris** [Cerzat43/vscode-twigcs#24]
Hey, recently I've noticed that I've lost errors highlighting feature - most probably because right now I have `1.3.0` version. After rolling back to `1.1.0`, errors are visible as before. Let me know how can I provide you more details.

**Comment by Cerzat43** [comment]
Hi @sirchris 
I think that I know what is your problem.
Can you say to me what is the twigcs version installed in your project with this command : `composer show -i | grep twigcs`
For me I have : 
```
friendsoftwig/twigcs                   v3.2.2   Checkstyle automation for...
```

**Comment by sirchris** [comment]
Same as yours - `v3.2.2`

**Comment by Cerzat43** [comment]
Are the errors visible with the `1.2.0` ?

**Comment by sirchris** [comment]
Nope

**Comment by Cerzat43** [comment]
Did you complete the option `twigcs.executablePath` ?

**Comment by sirchris** [comment]
Yes, I have this option set

**Comment by Cerzat43** [comment]
Is it something like : `./vendor/bin/twigcs` the twigcs in your project, or is it a global path ?

**Comment by sirchris** [comment]
Global path, something like `"twigcs.executablePath": "~/PATH_TO_THE_PROJECT/vendor/friendsoftwig/twigcs/bin/twigcs"`

And as I mentioned, without modifying it, everything works with `v1.1.0`

**Comment by sirchris** [comment]
Hey @Cerzat43, any news? :)

**Comment by Cerzat43** [comment]
I try to take a look this weekend or next week @sirchris.

**Comment by Cerzat43** [comment]
Hi @sirchris,
To help me, can you test to add a `lint` parameter at the end of your `twigcs.executablePath`  with the last version of the extension ? Like :
```
"twigcs.executablePath": "~/PATH_TO_THE_PROJECT/vendor/friendsoftwig/twigcs/bin/twigcs lint"
```
The `lint` parameter was mandatory before the friendsoftwig/twigcs v3.1.0, it has become deprecated. 
I removed this parameter in the version v1.2.0 of the extension.

I know that you use the v3.2.2 but I have to be sure that it's not this problem.

**Comment by sirchris** [comment]
Yep, this is it!!! After adding this param everything started to work :)

**Comment by Cerzat43** [comment]
Thanks for your response.

So it's strange, because this parameter isn't mandatory with the version 3.2.2 of `friendsoftwig/twigcs`.
Are you sure you don't have 2 versions of twigcs installed : one in the project and a second globally ?

**Comment by sirchris** [comment]
Yes, moreover, this is not only my problem as I have talked to a few colleagues working on other projects and they have the same issue after the package upgrade ¯\_(ツ)_/¯

**Comment by Cerzat43** [comment]
Ok, thanks for your message.
I will try to find a solution to this problem. Before this, you can add the `lint` parameter.

**Comment by sirchris** [comment]
One more question, have you heard or do you know a similar `twig linter` that is working with `PHPStorm`?

**Comment by Cerzat43** [comment]
Hi @sirchris,
It seems to me that there is a plugin dedicated to twig : 
![Capture du 2020-11-25 09-25-06](https://user-images.githubusercontent.com/11573049/100201503-6d963c80-2f00-11eb-9d1a-9277390d8c9e.png)

After installing this plugin, you should have some options in the "Coding Style" section : 
![Capture du 2020-11-25 09-23-28](https://user-images.githubusercontent.com/11573049/100201688-a1716200-2f00-11eb-97ac-9209e7c1b5f6.png)
![Capture du 2020-11-25 09-23-40](https://user-images.githubusercontent.com/11573049/100201702-a59d7f80-2f00-11eb-9715-930d14722192.png)

I know someone who uses PHPstorm and who shared the screens with me.

**Comment by Cerzat43** [comment]
Hi @sirchris,
There is a plugin dedicated to twig : 
![Capture du 2020-11-25 09-25-06](https://user-images.githubusercontent.com/11573049/100201503-6d963c80-2f00-11eb-9d1a-9277390d8c9e.png)

After installing this plugin, you should have some options in the "Coding Style" section : 
![Capture du 2020-11-25 09-23-28](https://user-images.githubusercontent.com/11573049/100201688-a1716200-2f00-11eb-97ac-9209e7c1b5f6.png)
![Capture du 2020-11-25 09-23-40](https://user-images.githubusercontent.com/11573049/100201702-a59d7f80-2f00-11eb-9715-930d14722192.png)

I know someone who uses PHPstorm and who shared the screens with me.

It seemed to me that it was possible to put the command line `./vendor/bin/twigcs`... I will try to find the info.
