### ISSUE TITLE
Linter view question

### ISSUE THREAD

**Issue by Adrian-Samuel** [Cerzat43/vscode-twigcs#7]
Hey, on the extension on description and picture, it shows the twig errors being displayed from the "problem section":

![screen shot 2018-04-27 at 17 11 30](https://user-images.githubusercontent.com/31516988/39373014-1f68e87c-4a3e-11e8-9d89-d5d2b1573e4e.png)

However on VScode it looks like this:
<img width="658" alt="screen shot 2018-04-27 at 17 10 05" src="https://user-images.githubusercontent.com/31516988/39372968-f9b245ba-4a3d-11e8-877f-e2a174a81e9d.png">

Is there something I can do to change that? Since the error message doesn't disappear like other linter tools once I make the change

**Comment by Cerzat43** [comment]
Hi @Adrian-Samuel 

I may have an idea about the cause of this problem. I will do different tests and push an update.

Thanks for your issue.

**Comment by Adrian-Samuel** [comment]
Hey @Cyril!

Thank for looking into this! :) Looking forward to it :D

Kind Regards,

**Comment by cyril** [comment]
You're welcome, @Adrian-Samuel.

**Comment by Cerzat43** [comment]
Hi @Adrian-Samuel 

Can you update the twigcs extension (v0.4.2) and check that the errors are no longer notified but listed in "problem section" ?

Thanks
